%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'RP_omega';
M_.dynare_version = '4.5.7';
oo_.dynare_version = '4.5.7';
options_.dynare_version = '4.5.7';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('RP_omega.log');
M_.exo_names = 'z_shk';
M_.exo_names_tex = 'z\_shk';
M_.exo_names_long = 'z_shk';
M_.exo_names = char(M_.exo_names, 'mp_shk');
M_.exo_names_tex = char(M_.exo_names_tex, 'mp\_shk');
M_.exo_names_long = char(M_.exo_names_long, 'mp_shk');
M_.exo_names = char(M_.exo_names, 'bk_shk');
M_.exo_names_tex = char(M_.exo_names_tex, 'bk\_shk');
M_.exo_names_long = char(M_.exo_names_long, 'bk_shk');
M_.exo_names = char(M_.exo_names, 'qe_shk');
M_.exo_names_tex = char(M_.exo_names_tex, 'qe\_shk');
M_.exo_names_long = char(M_.exo_names_long, 'qe_shk');
M_.endo_names = 'ch';
M_.endo_names_tex = 'ch';
M_.endo_names_long = 'ch';
M_.endo_names = char(M_.endo_names, 'Ce');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ce');
M_.endo_names_long = char(M_.endo_names_long, 'Ce');
M_.endo_names = char(M_.endo_names, 'Cb');
M_.endo_names_tex = char(M_.endo_names_tex, 'Cb');
M_.endo_names_long = char(M_.endo_names_long, 'Cb');
M_.endo_names = char(M_.endo_names, 'H');
M_.endo_names_tex = char(M_.endo_names_tex, 'H');
M_.endo_names_long = char(M_.endo_names_long, 'H');
M_.endo_names = char(M_.endo_names, 'Y');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y');
M_.endo_names_long = char(M_.endo_names_long, 'Y');
M_.endo_names = char(M_.endo_names, 'I');
M_.endo_names_tex = char(M_.endo_names_tex, 'I');
M_.endo_names_long = char(M_.endo_names_long, 'I');
M_.endo_names = char(M_.endo_names, 'bigN');
M_.endo_names_tex = char(M_.endo_names_tex, 'bigN');
M_.endo_names_long = char(M_.endo_names_long, 'bigN');
M_.endo_names = char(M_.endo_names, 'bigA');
M_.endo_names_tex = char(M_.endo_names_tex, 'bigA');
M_.endo_names_long = char(M_.endo_names_long, 'bigA');
M_.endo_names = char(M_.endo_names, 'smallb');
M_.endo_names_tex = char(M_.endo_names_tex, 'smallb');
M_.endo_names_long = char(M_.endo_names_long, 'smallb');
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, 'q');
M_.endo_names_long = char(M_.endo_names_long, 'q');
M_.endo_names = char(M_.endo_names, 'rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'rk');
M_.endo_names_long = char(M_.endo_names_long, 'rk');
M_.endo_names = char(M_.endo_names, 'infl');
M_.endo_names_tex = char(M_.endo_names_tex, 'infl');
M_.endo_names_long = char(M_.endo_names_long, 'infl');
M_.endo_names = char(M_.endo_names, 'w_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'w\_h');
M_.endo_names_long = char(M_.endo_names_long, 'w_h');
M_.endo_names = char(M_.endo_names, 'w_e');
M_.endo_names_tex = char(M_.endo_names_tex, 'w\_e');
M_.endo_names_long = char(M_.endo_names_long, 'w_e');
M_.endo_names = char(M_.endo_names, 'w_b');
M_.endo_names_tex = char(M_.endo_names_tex, 'w\_b');
M_.endo_names_long = char(M_.endo_names_long, 'w_b');
M_.endo_names = char(M_.endo_names, 'Rd');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rd');
M_.endo_names_long = char(M_.endo_names_long, 'Rd');
M_.endo_names = char(M_.endo_names, 'Ra');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ra');
M_.endo_names_long = char(M_.endo_names_long, 'Ra');
M_.endo_names = char(M_.endo_names, 'lam');
M_.endo_names_tex = char(M_.endo_names_tex, 'lam');
M_.endo_names_long = char(M_.endo_names_long, 'lam');
M_.endo_names = char(M_.endo_names, 'mu');
M_.endo_names_tex = char(M_.endo_names_tex, 'mu');
M_.endo_names_long = char(M_.endo_names_long, 'mu');
M_.endo_names = char(M_.endo_names, 'p');
M_.endo_names_tex = char(M_.endo_names_tex, 'p');
M_.endo_names_long = char(M_.endo_names_long, 'p');
M_.endo_names = char(M_.endo_names, 'TL');
M_.endo_names_tex = char(M_.endo_names_tex, 'TL');
M_.endo_names_long = char(M_.endo_names_long, 'TL');
M_.endo_names = char(M_.endo_names, 'mc');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc');
M_.endo_names_long = char(M_.endo_names_long, 'mc');
M_.endo_names = char(M_.endo_names, 's');
M_.endo_names_tex = char(M_.endo_names_tex, 's');
M_.endo_names_long = char(M_.endo_names_long, 's');
M_.endo_names = char(M_.endo_names, 'mgrowth');
M_.endo_names_tex = char(M_.endo_names_tex, 'mgrowth');
M_.endo_names_long = char(M_.endo_names_long, 'mgrowth');
M_.endo_names = char(M_.endo_names, 'expinfl');
M_.endo_names_tex = char(M_.endo_names_tex, 'expinfl');
M_.endo_names_long = char(M_.endo_names_long, 'expinfl');
M_.endo_names = char(M_.endo_names, 'smalld');
M_.endo_names_tex = char(M_.endo_names_tex, 'smalld');
M_.endo_names_long = char(M_.endo_names_long, 'smalld');
M_.endo_names = char(M_.endo_names, 'gY');
M_.endo_names_tex = char(M_.endo_names_tex, 'gY');
M_.endo_names_long = char(M_.endo_names_long, 'gY');
M_.endo_names = char(M_.endo_names, 'totC');
M_.endo_names_tex = char(M_.endo_names_tex, 'totC');
M_.endo_names_long = char(M_.endo_names_long, 'totC');
M_.endo_names = char(M_.endo_names, 'u');
M_.endo_names_tex = char(M_.endo_names_tex, 'u');
M_.endo_names_long = char(M_.endo_names_long, 'u');
M_.endo_names = char(M_.endo_names, 'keff');
M_.endo_names_tex = char(M_.endo_names_tex, 'keff');
M_.endo_names_long = char(M_.endo_names_long, 'keff');
M_.endo_names = char(M_.endo_names, 'K');
M_.endo_names_tex = char(M_.endo_names_tex, 'K');
M_.endo_names_long = char(M_.endo_names_long, 'K');
M_.endo_names = char(M_.endo_names, 'Kb');
M_.endo_names_tex = char(M_.endo_names_tex, 'Kb');
M_.endo_names_long = char(M_.endo_names_long, 'Kb');
M_.endo_names = char(M_.endo_names, 'Ke');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ke');
M_.endo_names_long = char(M_.endo_names_long, 'Ke');
M_.endo_names = char(M_.endo_names, 'ptilde');
M_.endo_names_tex = char(M_.endo_names_tex, 'ptilde');
M_.endo_names_long = char(M_.endo_names_long, 'ptilde');
M_.endo_names = char(M_.endo_names, 'nump');
M_.endo_names_tex = char(M_.endo_names_tex, 'nump');
M_.endo_names_long = char(M_.endo_names_long, 'nump');
M_.endo_names = char(M_.endo_names, 'denp');
M_.endo_names_tex = char(M_.endo_names_tex, 'denp');
M_.endo_names_long = char(M_.endo_names_long, 'denp');
M_.endo_names = char(M_.endo_names, 'wtilde');
M_.endo_names_tex = char(M_.endo_names_tex, 'wtilde');
M_.endo_names_long = char(M_.endo_names_long, 'wtilde');
M_.endo_names = char(M_.endo_names, 'numw');
M_.endo_names_tex = char(M_.endo_names_tex, 'numw');
M_.endo_names_long = char(M_.endo_names_long, 'numw');
M_.endo_names = char(M_.endo_names, 'denw');
M_.endo_names_tex = char(M_.endo_names_tex, 'denw');
M_.endo_names_long = char(M_.endo_names_long, 'denw');
M_.endo_names = char(M_.endo_names, 'lz');
M_.endo_names_tex = char(M_.endo_names_tex, 'lz');
M_.endo_names_long = char(M_.endo_names_long, 'lz');
M_.endo_names = char(M_.endo_names, 'lmp');
M_.endo_names_tex = char(M_.endo_names_tex, 'lmp');
M_.endo_names_long = char(M_.endo_names_long, 'lmp');
M_.endo_names = char(M_.endo_names, 'lbk');
M_.endo_names_tex = char(M_.endo_names_tex, 'lbk');
M_.endo_names_long = char(M_.endo_names_long, 'lbk');
M_.endo_names = char(M_.endo_names, 'log_y');
M_.endo_names_tex = char(M_.endo_names_tex, 'log\_y');
M_.endo_names_long = char(M_.endo_names_long, 'log_y');
M_.endo_names = char(M_.endo_names, 'log_I');
M_.endo_names_tex = char(M_.endo_names_tex, 'log\_I');
M_.endo_names_long = char(M_.endo_names_long, 'log_I');
M_.endo_names = char(M_.endo_names, 'gammag');
M_.endo_names_tex = char(M_.endo_names_tex, 'gammag');
M_.endo_names_long = char(M_.endo_names_long, 'gammag');
M_.endo_names = char(M_.endo_names, 'alpha');
M_.endo_names_tex = char(M_.endo_names_tex, 'alpha');
M_.endo_names_long = char(M_.endo_names_long, 'alpha');
M_.endo_names = char(M_.endo_names, 'rnot');
M_.endo_names_tex = char(M_.endo_names_tex, 'rnot');
M_.endo_names_long = char(M_.endo_names_long, 'rnot');
M_.endo_names = char(M_.endo_names, 'CBBS');
M_.endo_names_tex = char(M_.endo_names_tex, 'CBBS');
M_.endo_names_long = char(M_.endo_names_long, 'CBBS');
M_.endo_names = char(M_.endo_names, 'lqe');
M_.endo_names_tex = char(M_.endo_names_tex, 'lqe');
M_.endo_names_long = char(M_.endo_names_long, 'lqe');
M_.endo_names = char(M_.endo_names, 'bdp');
M_.endo_names_tex = char(M_.endo_names_tex, 'bdp');
M_.endo_names_long = char(M_.endo_names_long, 'bdp');
M_.endo_names = char(M_.endo_names, 'inflexp1');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp1');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp1');
M_.endo_names = char(M_.endo_names, 'inflexp2');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp2');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp2');
M_.endo_names = char(M_.endo_names, 'inflexp3');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp3');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp3');
M_.endo_names = char(M_.endo_names, 'inflexp4');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp4');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp4');
M_.endo_names = char(M_.endo_names, 'inflexp5');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp5');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp5');
M_.endo_names = char(M_.endo_names, 'inflexp6');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp6');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp6');
M_.endo_names = char(M_.endo_names, 'inflexp7');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp7');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp7');
M_.endo_names = char(M_.endo_names, 'inflexp8');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp8');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp8');
M_.endo_names = char(M_.endo_names, 'inflexp9');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp9');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp9');
M_.endo_names = char(M_.endo_names, 'inflexp10');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp10');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp10');
M_.endo_names = char(M_.endo_names, 'inflexp11');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp11');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp11');
M_.endo_names = char(M_.endo_names, 'inflexp12');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp12');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp12');
M_.endo_names = char(M_.endo_names, 'inflexp13');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp13');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp13');
M_.endo_names = char(M_.endo_names, 'inflexp14');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp14');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp14');
M_.endo_names = char(M_.endo_names, 'inflexp15');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp15');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp15');
M_.endo_names = char(M_.endo_names, 'inflexp16');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp16');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp16');
M_.endo_names = char(M_.endo_names, 'inflexp17');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp17');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp17');
M_.endo_names = char(M_.endo_names, 'inflexp18');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp18');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp18');
M_.endo_names = char(M_.endo_names, 'inflexp19');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp19');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp19');
M_.endo_names = char(M_.endo_names, 'inflexp20');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp20');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp20');
M_.endo_names = char(M_.endo_names, 'inflexp21');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp21');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp21');
M_.endo_names = char(M_.endo_names, 'inflexp22');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp22');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp22');
M_.endo_names = char(M_.endo_names, 'inflexp23');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp23');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp23');
M_.endo_names = char(M_.endo_names, 'inflexp24');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp24');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp24');
M_.endo_names = char(M_.endo_names, 'inflexp25');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp25');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp25');
M_.endo_names = char(M_.endo_names, 'inflexp26');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp26');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp26');
M_.endo_names = char(M_.endo_names, 'inflexp27');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp27');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp27');
M_.endo_names = char(M_.endo_names, 'inflexp28');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp28');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp28');
M_.endo_names = char(M_.endo_names, 'inflexp29');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp29');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp29');
M_.endo_names = char(M_.endo_names, 'inflexp30');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp30');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp30');
M_.endo_names = char(M_.endo_names, 'inflexp31');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp31');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp31');
M_.endo_names = char(M_.endo_names, 'inflexp32');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp32');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp32');
M_.endo_names = char(M_.endo_names, 'inflexp33');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp33');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp33');
M_.endo_names = char(M_.endo_names, 'inflexp34');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp34');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp34');
M_.endo_names = char(M_.endo_names, 'inflexp35');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp35');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp35');
M_.endo_names = char(M_.endo_names, 'inflexp36');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp36');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp36');
M_.endo_names = char(M_.endo_names, 'inflexp37');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp37');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp37');
M_.endo_names = char(M_.endo_names, 'inflexp38');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp38');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp38');
M_.endo_names = char(M_.endo_names, 'inflexp39');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp39');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp39');
M_.endo_names = char(M_.endo_names, 'inflexp40');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflexp40');
M_.endo_names_long = char(M_.endo_names_long, 'inflexp40');
M_.endo_names = char(M_.endo_names, 'Rexp1');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp1');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp1');
M_.endo_names = char(M_.endo_names, 'Rexp2');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp2');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp2');
M_.endo_names = char(M_.endo_names, 'Rexp3');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp3');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp3');
M_.endo_names = char(M_.endo_names, 'Rexp4');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp4');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp4');
M_.endo_names = char(M_.endo_names, 'Rexp5');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp5');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp5');
M_.endo_names = char(M_.endo_names, 'Rexp6');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp6');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp6');
M_.endo_names = char(M_.endo_names, 'Rexp7');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp7');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp7');
M_.endo_names = char(M_.endo_names, 'Rexp8');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp8');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp8');
M_.endo_names = char(M_.endo_names, 'Rexp9');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp9');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp9');
M_.endo_names = char(M_.endo_names, 'Rexp10');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp10');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp10');
M_.endo_names = char(M_.endo_names, 'Rexp11');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp11');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp11');
M_.endo_names = char(M_.endo_names, 'Rexp12');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp12');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp12');
M_.endo_names = char(M_.endo_names, 'Rexp13');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp13');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp13');
M_.endo_names = char(M_.endo_names, 'Rexp14');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp14');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp14');
M_.endo_names = char(M_.endo_names, 'Rexp15');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp15');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp15');
M_.endo_names = char(M_.endo_names, 'Rexp16');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp16');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp16');
M_.endo_names = char(M_.endo_names, 'Rexp17');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp17');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp17');
M_.endo_names = char(M_.endo_names, 'Rexp18');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp18');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp18');
M_.endo_names = char(M_.endo_names, 'Rexp19');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp19');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp19');
M_.endo_names = char(M_.endo_names, 'Rexp20');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp20');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp20');
M_.endo_names = char(M_.endo_names, 'Rexp21');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp21');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp21');
M_.endo_names = char(M_.endo_names, 'Rexp22');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp22');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp22');
M_.endo_names = char(M_.endo_names, 'Rexp23');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp23');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp23');
M_.endo_names = char(M_.endo_names, 'Rexp24');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp24');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp24');
M_.endo_names = char(M_.endo_names, 'Rexp25');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp25');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp25');
M_.endo_names = char(M_.endo_names, 'Rexp26');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp26');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp26');
M_.endo_names = char(M_.endo_names, 'Rexp27');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp27');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp27');
M_.endo_names = char(M_.endo_names, 'Rexp28');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp28');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp28');
M_.endo_names = char(M_.endo_names, 'Rexp29');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp29');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp29');
M_.endo_names = char(M_.endo_names, 'Rexp30');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp30');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp30');
M_.endo_names = char(M_.endo_names, 'Rexp31');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp31');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp31');
M_.endo_names = char(M_.endo_names, 'Rexp32');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp32');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp32');
M_.endo_names = char(M_.endo_names, 'Rexp33');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp33');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp33');
M_.endo_names = char(M_.endo_names, 'Rexp34');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp34');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp34');
M_.endo_names = char(M_.endo_names, 'Rexp35');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp35');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp35');
M_.endo_names = char(M_.endo_names, 'Rexp36');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp36');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp36');
M_.endo_names = char(M_.endo_names, 'Rexp37');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp37');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp37');
M_.endo_names = char(M_.endo_names, 'Rexp38');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp38');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp38');
M_.endo_names = char(M_.endo_names, 'Rexp39');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp39');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp39');
M_.endo_names = char(M_.endo_names, 'Rexp40');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rexp40');
M_.endo_names_long = char(M_.endo_names_long, 'Rexp40');
M_.endo_names = char(M_.endo_names, 'util');
M_.endo_names_tex = char(M_.endo_names_tex, 'util');
M_.endo_names_long = char(M_.endo_names_long, 'util');
M_.endo_names = char(M_.endo_names, 'welf');
M_.endo_names_tex = char(M_.endo_names_tex, 'welf');
M_.endo_names_long = char(M_.endo_names_long, 'welf');
M_.endo_names = char(M_.endo_names, 'MULT_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_1');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_1');
M_.endo_names = char(M_.endo_names, 'MULT_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_2');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_2');
M_.endo_names = char(M_.endo_names, 'MULT_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_3');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_3');
M_.endo_names = char(M_.endo_names, 'MULT_4');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_4');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_4');
M_.endo_names = char(M_.endo_names, 'MULT_5');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_5');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_5');
M_.endo_names = char(M_.endo_names, 'MULT_6');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_6');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_6');
M_.endo_names = char(M_.endo_names, 'MULT_7');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_7');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_7');
M_.endo_names = char(M_.endo_names, 'MULT_8');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_8');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_8');
M_.endo_names = char(M_.endo_names, 'MULT_9');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_9');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_9');
M_.endo_names = char(M_.endo_names, 'MULT_10');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_10');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_10');
M_.endo_names = char(M_.endo_names, 'MULT_11');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_11');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_11');
M_.endo_names = char(M_.endo_names, 'MULT_12');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_12');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_12');
M_.endo_names = char(M_.endo_names, 'MULT_13');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_13');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_13');
M_.endo_names = char(M_.endo_names, 'MULT_14');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_14');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_14');
M_.endo_names = char(M_.endo_names, 'MULT_15');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_15');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_15');
M_.endo_names = char(M_.endo_names, 'MULT_16');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_16');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_16');
M_.endo_names = char(M_.endo_names, 'MULT_17');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_17');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_17');
M_.endo_names = char(M_.endo_names, 'MULT_18');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_18');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_18');
M_.endo_names = char(M_.endo_names, 'MULT_19');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_19');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_19');
M_.endo_names = char(M_.endo_names, 'MULT_20');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_20');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_20');
M_.endo_names = char(M_.endo_names, 'MULT_21');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_21');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_21');
M_.endo_names = char(M_.endo_names, 'MULT_22');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_22');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_22');
M_.endo_names = char(M_.endo_names, 'MULT_23');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_23');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_23');
M_.endo_names = char(M_.endo_names, 'MULT_24');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_24');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_24');
M_.endo_names = char(M_.endo_names, 'MULT_25');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_25');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_25');
M_.endo_names = char(M_.endo_names, 'MULT_26');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_26');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_26');
M_.endo_names = char(M_.endo_names, 'MULT_27');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_27');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_27');
M_.endo_names = char(M_.endo_names, 'MULT_28');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_28');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_28');
M_.endo_names = char(M_.endo_names, 'MULT_29');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_29');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_29');
M_.endo_names = char(M_.endo_names, 'MULT_30');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_30');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_30');
M_.endo_names = char(M_.endo_names, 'MULT_31');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_31');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_31');
M_.endo_names = char(M_.endo_names, 'MULT_32');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_32');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_32');
M_.endo_names = char(M_.endo_names, 'MULT_33');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_33');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_33');
M_.endo_names = char(M_.endo_names, 'MULT_34');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_34');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_34');
M_.endo_names = char(M_.endo_names, 'MULT_35');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_35');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_35');
M_.endo_names = char(M_.endo_names, 'MULT_36');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_36');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_36');
M_.endo_names = char(M_.endo_names, 'MULT_37');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_37');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_37');
M_.endo_names = char(M_.endo_names, 'MULT_38');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_38');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_38');
M_.endo_names = char(M_.endo_names, 'MULT_39');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_39');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_39');
M_.endo_names = char(M_.endo_names, 'MULT_40');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_40');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_40');
M_.endo_names = char(M_.endo_names, 'MULT_41');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_41');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_41');
M_.endo_names = char(M_.endo_names, 'MULT_42');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_42');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_42');
M_.endo_names = char(M_.endo_names, 'MULT_43');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_43');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_43');
M_.endo_names = char(M_.endo_names, 'MULT_44');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_44');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_44');
M_.endo_names = char(M_.endo_names, 'MULT_45');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_45');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_45');
M_.endo_names = char(M_.endo_names, 'MULT_46');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_46');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_46');
M_.endo_names = char(M_.endo_names, 'MULT_47');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_47');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_47');
M_.endo_names = char(M_.endo_names, 'MULT_48');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_48');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_48');
M_.endo_names = char(M_.endo_names, 'MULT_49');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_49');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_49');
M_.endo_names = char(M_.endo_names, 'MULT_50');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_50');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_50');
M_.endo_names = char(M_.endo_names, 'MULT_51');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_51');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_51');
M_.endo_names = char(M_.endo_names, 'MULT_52');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_52');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_52');
M_.endo_names = char(M_.endo_names, 'MULT_53');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_53');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_53');
M_.endo_names = char(M_.endo_names, 'MULT_54');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_54');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_54');
M_.endo_names = char(M_.endo_names, 'MULT_55');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_55');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_55');
M_.endo_names = char(M_.endo_names, 'MULT_56');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_56');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_56');
M_.endo_names = char(M_.endo_names, 'MULT_57');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_57');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_57');
M_.endo_names = char(M_.endo_names, 'MULT_58');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_58');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_58');
M_.endo_names = char(M_.endo_names, 'MULT_59');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_59');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_59');
M_.endo_names = char(M_.endo_names, 'MULT_60');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_60');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_60');
M_.endo_names = char(M_.endo_names, 'MULT_61');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_61');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_61');
M_.endo_names = char(M_.endo_names, 'MULT_62');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_62');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_62');
M_.endo_names = char(M_.endo_names, 'MULT_63');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_63');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_63');
M_.endo_names = char(M_.endo_names, 'MULT_64');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_64');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_64');
M_.endo_names = char(M_.endo_names, 'MULT_65');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_65');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_65');
M_.endo_names = char(M_.endo_names, 'MULT_66');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_66');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_66');
M_.endo_names = char(M_.endo_names, 'MULT_67');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_67');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_67');
M_.endo_names = char(M_.endo_names, 'MULT_68');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_68');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_68');
M_.endo_names = char(M_.endo_names, 'MULT_69');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_69');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_69');
M_.endo_names = char(M_.endo_names, 'MULT_70');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_70');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_70');
M_.endo_names = char(M_.endo_names, 'MULT_71');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_71');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_71');
M_.endo_names = char(M_.endo_names, 'MULT_72');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_72');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_72');
M_.endo_names = char(M_.endo_names, 'MULT_73');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_73');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_73');
M_.endo_names = char(M_.endo_names, 'MULT_74');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_74');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_74');
M_.endo_names = char(M_.endo_names, 'MULT_75');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_75');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_75');
M_.endo_names = char(M_.endo_names, 'MULT_76');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_76');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_76');
M_.endo_names = char(M_.endo_names, 'MULT_77');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_77');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_77');
M_.endo_names = char(M_.endo_names, 'MULT_78');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_78');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_78');
M_.endo_names = char(M_.endo_names, 'MULT_79');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_79');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_79');
M_.endo_names = char(M_.endo_names, 'MULT_80');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_80');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_80');
M_.endo_names = char(M_.endo_names, 'MULT_81');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_81');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_81');
M_.endo_names = char(M_.endo_names, 'MULT_82');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_82');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_82');
M_.endo_names = char(M_.endo_names, 'MULT_83');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_83');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_83');
M_.endo_names = char(M_.endo_names, 'MULT_84');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_84');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_84');
M_.endo_names = char(M_.endo_names, 'MULT_85');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_85');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_85');
M_.endo_names = char(M_.endo_names, 'MULT_86');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_86');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_86');
M_.endo_names = char(M_.endo_names, 'MULT_87');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_87');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_87');
M_.endo_names = char(M_.endo_names, 'MULT_88');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_88');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_88');
M_.endo_names = char(M_.endo_names, 'MULT_89');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_89');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_89');
M_.endo_names = char(M_.endo_names, 'MULT_90');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_90');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_90');
M_.endo_names = char(M_.endo_names, 'MULT_91');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_91');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_91');
M_.endo_names = char(M_.endo_names, 'MULT_92');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_92');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_92');
M_.endo_names = char(M_.endo_names, 'MULT_93');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_93');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_93');
M_.endo_names = char(M_.endo_names, 'MULT_94');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_94');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_94');
M_.endo_names = char(M_.endo_names, 'MULT_95');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_95');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_95');
M_.endo_names = char(M_.endo_names, 'MULT_96');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_96');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_96');
M_.endo_names = char(M_.endo_names, 'MULT_97');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_97');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_97');
M_.endo_names = char(M_.endo_names, 'MULT_98');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_98');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_98');
M_.endo_names = char(M_.endo_names, 'MULT_99');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_99');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_99');
M_.endo_names = char(M_.endo_names, 'MULT_100');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_100');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_100');
M_.endo_names = char(M_.endo_names, 'MULT_101');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_101');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_101');
M_.endo_names = char(M_.endo_names, 'MULT_102');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_102');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_102');
M_.endo_names = char(M_.endo_names, 'MULT_103');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_103');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_103');
M_.endo_names = char(M_.endo_names, 'MULT_104');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_104');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_104');
M_.endo_names = char(M_.endo_names, 'MULT_105');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_105');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_105');
M_.endo_names = char(M_.endo_names, 'MULT_106');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_106');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_106');
M_.endo_names = char(M_.endo_names, 'MULT_107');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_107');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_107');
M_.endo_names = char(M_.endo_names, 'MULT_108');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_108');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_108');
M_.endo_names = char(M_.endo_names, 'MULT_109');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_109');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_109');
M_.endo_names = char(M_.endo_names, 'MULT_110');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_110');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_110');
M_.endo_names = char(M_.endo_names, 'MULT_111');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_111');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_111');
M_.endo_names = char(M_.endo_names, 'MULT_112');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_112');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_112');
M_.endo_names = char(M_.endo_names, 'MULT_113');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_113');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_113');
M_.endo_names = char(M_.endo_names, 'MULT_114');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_114');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_114');
M_.endo_names = char(M_.endo_names, 'MULT_115');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_115');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_115');
M_.endo_names = char(M_.endo_names, 'MULT_116');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_116');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_116');
M_.endo_names = char(M_.endo_names, 'MULT_117');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_117');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_117');
M_.endo_names = char(M_.endo_names, 'MULT_118');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_118');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_118');
M_.endo_names = char(M_.endo_names, 'MULT_119');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_119');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_119');
M_.endo_names = char(M_.endo_names, 'MULT_120');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_120');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_120');
M_.endo_names = char(M_.endo_names, 'MULT_121');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_121');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_121');
M_.endo_names = char(M_.endo_names, 'MULT_122');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_122');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_122');
M_.endo_names = char(M_.endo_names, 'MULT_123');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_123');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_123');
M_.endo_names = char(M_.endo_names, 'MULT_124');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_124');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_124');
M_.endo_names = char(M_.endo_names, 'MULT_125');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_125');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_125');
M_.endo_names = char(M_.endo_names, 'MULT_126');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_126');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_126');
M_.endo_names = char(M_.endo_names, 'MULT_127');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_127');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_127');
M_.endo_names = char(M_.endo_names, 'MULT_128');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_128');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_128');
M_.endo_names = char(M_.endo_names, 'MULT_129');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_129');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_129');
M_.endo_names = char(M_.endo_names, 'MULT_130');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_130');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_130');
M_.endo_names = char(M_.endo_names, 'MULT_131');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_131');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_131');
M_.endo_names = char(M_.endo_names, 'MULT_132');
M_.endo_names_tex = char(M_.endo_names_tex, 'MULT\_132');
M_.endo_names_long = char(M_.endo_names_long, 'MULT_132');
M_.endo_partitions = struct();
M_.param_names = 'habit';
M_.param_names_tex = 'habit';
M_.param_names_long = 'habit';
M_.param_names = char(M_.param_names, 'bet');
M_.param_names_tex = char(M_.param_names_tex, 'bet');
M_.param_names_long = char(M_.param_names_long, 'bet');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'reta');
M_.param_names_tex = char(M_.param_names_tex, 'reta');
M_.param_names_long = char(M_.param_names_long, 'reta');
M_.param_names = char(M_.param_names, 'psi_l');
M_.param_names_tex = char(M_.param_names_tex, 'psi\_l');
M_.param_names_long = char(M_.param_names_long, 'psi_l');
M_.param_names = char(M_.param_names, 'elas_l');
M_.param_names_tex = char(M_.param_names_tex, 'elas\_l');
M_.param_names_long = char(M_.param_names_long, 'elas_l');
M_.param_names = char(M_.param_names, 'chi1');
M_.param_names_tex = char(M_.param_names_tex, 'chi1');
M_.param_names_long = char(M_.param_names_long, 'chi1');
M_.param_names = char(M_.param_names, 'chi2');
M_.param_names_tex = char(M_.param_names_tex, 'chi2');
M_.param_names_long = char(M_.param_names_long, 'chi2');
M_.param_names = char(M_.param_names, 'pi_ss');
M_.param_names_tex = char(M_.param_names_tex, 'pi\_ss');
M_.param_names_long = char(M_.param_names_long, 'pi_ss');
M_.param_names = char(M_.param_names, 'xi_w');
M_.param_names_tex = char(M_.param_names_tex, 'xi\_w');
M_.param_names_long = char(M_.param_names_long, 'xi_w');
M_.param_names = char(M_.param_names, 'phi_w');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_w');
M_.param_names_long = char(M_.param_names_long, 'phi_w');
M_.param_names = char(M_.param_names, 'mark_w');
M_.param_names_tex = char(M_.param_names_tex, 'mark\_w');
M_.param_names_long = char(M_.param_names_long, 'mark_w');
M_.param_names = char(M_.param_names, 'eta_h');
M_.param_names_tex = char(M_.param_names_tex, 'eta\_h');
M_.param_names_long = char(M_.param_names_long, 'eta_h');
M_.param_names = char(M_.param_names, 'eta_e');
M_.param_names_tex = char(M_.param_names_tex, 'eta\_e');
M_.param_names_long = char(M_.param_names_long, 'eta_e');
M_.param_names = char(M_.param_names, 'eta_b');
M_.param_names_tex = char(M_.param_names_tex, 'eta\_b');
M_.param_names_long = char(M_.param_names_long, 'eta_b');
M_.param_names = char(M_.param_names, 'xi_p');
M_.param_names_tex = char(M_.param_names_tex, 'xi\_p');
M_.param_names_long = char(M_.param_names_long, 'xi_p');
M_.param_names = char(M_.param_names, 'phi_p');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_p');
M_.param_names_long = char(M_.param_names_long, 'phi_p');
M_.param_names = char(M_.param_names, 'mark_p');
M_.param_names_tex = char(M_.param_names_tex, 'mark\_p');
M_.param_names_long = char(M_.param_names_long, 'mark_p');
M_.param_names = char(M_.param_names, 'theta_k');
M_.param_names_tex = char(M_.param_names_tex, 'theta\_k');
M_.param_names_long = char(M_.param_names_long, 'theta_k');
M_.param_names = char(M_.param_names, 'theta_h');
M_.param_names_tex = char(M_.param_names_tex, 'theta\_h');
M_.param_names_long = char(M_.param_names_long, 'theta_h');
M_.param_names = char(M_.param_names, 'theta_e');
M_.param_names_tex = char(M_.param_names_tex, 'theta\_e');
M_.param_names_long = char(M_.param_names_long, 'theta_e');
M_.param_names = char(M_.param_names, 'theta_b');
M_.param_names_tex = char(M_.param_names_tex, 'theta\_b');
M_.param_names_long = char(M_.param_names_long, 'theta_b');
M_.param_names = char(M_.param_names, 'bigR');
M_.param_names_tex = char(M_.param_names_tex, 'bigR');
M_.param_names_long = char(M_.param_names_long, 'bigR');
M_.param_names = char(M_.param_names, 'delalpha');
M_.param_names_tex = char(M_.param_names_tex, 'delalpha');
M_.param_names_long = char(M_.param_names_long, 'delalpha');
M_.param_names = char(M_.param_names, 'tau_b');
M_.param_names_tex = char(M_.param_names_tex, 'tau\_b');
M_.param_names_long = char(M_.param_names_long, 'tau_b');
M_.param_names = char(M_.param_names, 'tau_e');
M_.param_names_tex = char(M_.param_names_tex, 'tau\_e');
M_.param_names_long = char(M_.param_names_long, 'tau_e');
M_.param_names = char(M_.param_names, 'lam_r');
M_.param_names_tex = char(M_.param_names_tex, 'lam\_r');
M_.param_names_long = char(M_.param_names_long, 'lam_r');
M_.param_names = char(M_.param_names, 'lam_pi');
M_.param_names_tex = char(M_.param_names_tex, 'lam\_pi');
M_.param_names_long = char(M_.param_names_long, 'lam_pi');
M_.param_names = char(M_.param_names, 'lam_y');
M_.param_names_tex = char(M_.param_names_tex, 'lam\_y');
M_.param_names_long = char(M_.param_names_long, 'lam_y');
M_.param_names = char(M_.param_names, 'bigtheta');
M_.param_names_tex = char(M_.param_names_tex, 'bigtheta');
M_.param_names_long = char(M_.param_names_long, 'bigtheta');
M_.param_names = char(M_.param_names, 'bby');
M_.param_names_tex = char(M_.param_names_tex, 'bby');
M_.param_names_long = char(M_.param_names_long, 'bby');
M_.param_names = char(M_.param_names, 'nu');
M_.param_names_tex = char(M_.param_names_tex, 'nu');
M_.param_names_long = char(M_.param_names_long, 'nu');
M_.param_names = char(M_.param_names, 'rhoz');
M_.param_names_tex = char(M_.param_names_tex, 'rhoz');
M_.param_names_long = char(M_.param_names_long, 'rhoz');
M_.param_names = char(M_.param_names, 'rhomp');
M_.param_names_tex = char(M_.param_names_tex, 'rhomp');
M_.param_names_long = char(M_.param_names_long, 'rhomp');
M_.param_names = char(M_.param_names, 'rhobk');
M_.param_names_tex = char(M_.param_names_tex, 'rhobk');
M_.param_names_long = char(M_.param_names_long, 'rhobk');
M_.param_names = char(M_.param_names, 'sigmaz');
M_.param_names_tex = char(M_.param_names_tex, 'sigmaz');
M_.param_names_long = char(M_.param_names_long, 'sigmaz');
M_.param_names = char(M_.param_names, 'sigmamp');
M_.param_names_tex = char(M_.param_names_tex, 'sigmamp');
M_.param_names_long = char(M_.param_names_long, 'sigmamp');
M_.param_names = char(M_.param_names, 'sigmabk');
M_.param_names_tex = char(M_.param_names_tex, 'sigmabk');
M_.param_names_long = char(M_.param_names_long, 'sigmabk');
M_.param_names = char(M_.param_names, 'alpha_ss');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_ss');
M_.param_names_long = char(M_.param_names_long, 'alpha_ss');
M_.param_names = char(M_.param_names, 'mu_ss');
M_.param_names_tex = char(M_.param_names_tex, 'mu\_ss');
M_.param_names_long = char(M_.param_names_long, 'mu_ss');
M_.param_names = char(M_.param_names, 'omega');
M_.param_names_tex = char(M_.param_names_tex, 'omega');
M_.param_names_long = char(M_.param_names_long, 'omega');
M_.param_names = char(M_.param_names, 'varsigma');
M_.param_names_tex = char(M_.param_names_tex, 'varsigma');
M_.param_names_long = char(M_.param_names_long, 'varsigma');
M_.param_names = char(M_.param_names, 'epsb');
M_.param_names_tex = char(M_.param_names_tex, 'epsb');
M_.param_names_long = char(M_.param_names_long, 'epsb');
M_.param_names = char(M_.param_names, 'Btopbar');
M_.param_names_tex = char(M_.param_names_tex, 'Btopbar');
M_.param_names_long = char(M_.param_names_long, 'Btopbar');
M_.param_names = char(M_.param_names, 'Blowbar');
M_.param_names_tex = char(M_.param_names_tex, 'Blowbar');
M_.param_names_long = char(M_.param_names_long, 'Blowbar');
M_.param_names = char(M_.param_names, 'Chi');
M_.param_names_tex = char(M_.param_names_tex, 'Chi');
M_.param_names_long = char(M_.param_names_long, 'Chi');
M_.param_names = char(M_.param_names, 'CBBSp');
M_.param_names_tex = char(M_.param_names_tex, 'CBBSp');
M_.param_names_long = char(M_.param_names_long, 'CBBSp');
M_.param_names = char(M_.param_names, 'sigmaqe');
M_.param_names_tex = char(M_.param_names_tex, 'sigmaqe');
M_.param_names_long = char(M_.param_names_long, 'sigmaqe');
M_.param_names = char(M_.param_names, 'rhoqe');
M_.param_names_tex = char(M_.param_names_tex, 'rhoqe');
M_.param_names_long = char(M_.param_names_long, 'rhoqe');
M_.param_names = char(M_.param_names, 'optimal_policy_discount_factor');
M_.param_names_tex = char(M_.param_names_tex, 'optimal\_policy\_discount\_factor');
M_.param_names_long = char(M_.param_names_long, 'optimal_policy_discount_factor');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 4;
M_.endo_nbr = 264;
M_.param_nbr = 50;
M_.orig_endo_nbr = 132;
M_.aux_vars(1).endo_index = 133;
M_.aux_vars(1).type = 6;
M_.aux_vars(1).eq_nbr = 1;
M_.aux_vars(2).endo_index = 134;
M_.aux_vars(2).type = 6;
M_.aux_vars(2).eq_nbr = 2;
M_.aux_vars(3).endo_index = 135;
M_.aux_vars(3).type = 6;
M_.aux_vars(3).eq_nbr = 3;
M_.aux_vars(4).endo_index = 136;
M_.aux_vars(4).type = 6;
M_.aux_vars(4).eq_nbr = 4;
M_.aux_vars(5).endo_index = 137;
M_.aux_vars(5).type = 6;
M_.aux_vars(5).eq_nbr = 5;
M_.aux_vars(6).endo_index = 138;
M_.aux_vars(6).type = 6;
M_.aux_vars(6).eq_nbr = 6;
M_.aux_vars(7).endo_index = 139;
M_.aux_vars(7).type = 6;
M_.aux_vars(7).eq_nbr = 7;
M_.aux_vars(8).endo_index = 140;
M_.aux_vars(8).type = 6;
M_.aux_vars(8).eq_nbr = 8;
M_.aux_vars(9).endo_index = 141;
M_.aux_vars(9).type = 6;
M_.aux_vars(9).eq_nbr = 9;
M_.aux_vars(10).endo_index = 142;
M_.aux_vars(10).type = 6;
M_.aux_vars(10).eq_nbr = 10;
M_.aux_vars(11).endo_index = 143;
M_.aux_vars(11).type = 6;
M_.aux_vars(11).eq_nbr = 11;
M_.aux_vars(12).endo_index = 144;
M_.aux_vars(12).type = 6;
M_.aux_vars(12).eq_nbr = 12;
M_.aux_vars(13).endo_index = 145;
M_.aux_vars(13).type = 6;
M_.aux_vars(13).eq_nbr = 13;
M_.aux_vars(14).endo_index = 146;
M_.aux_vars(14).type = 6;
M_.aux_vars(14).eq_nbr = 14;
M_.aux_vars(15).endo_index = 147;
M_.aux_vars(15).type = 6;
M_.aux_vars(15).eq_nbr = 15;
M_.aux_vars(16).endo_index = 148;
M_.aux_vars(16).type = 6;
M_.aux_vars(16).eq_nbr = 16;
M_.aux_vars(17).endo_index = 149;
M_.aux_vars(17).type = 6;
M_.aux_vars(17).eq_nbr = 17;
M_.aux_vars(18).endo_index = 150;
M_.aux_vars(18).type = 6;
M_.aux_vars(18).eq_nbr = 18;
M_.aux_vars(19).endo_index = 151;
M_.aux_vars(19).type = 6;
M_.aux_vars(19).eq_nbr = 19;
M_.aux_vars(20).endo_index = 152;
M_.aux_vars(20).type = 6;
M_.aux_vars(20).eq_nbr = 20;
M_.aux_vars(21).endo_index = 153;
M_.aux_vars(21).type = 6;
M_.aux_vars(21).eq_nbr = 21;
M_.aux_vars(22).endo_index = 154;
M_.aux_vars(22).type = 6;
M_.aux_vars(22).eq_nbr = 22;
M_.aux_vars(23).endo_index = 155;
M_.aux_vars(23).type = 6;
M_.aux_vars(23).eq_nbr = 23;
M_.aux_vars(24).endo_index = 156;
M_.aux_vars(24).type = 6;
M_.aux_vars(24).eq_nbr = 24;
M_.aux_vars(25).endo_index = 157;
M_.aux_vars(25).type = 6;
M_.aux_vars(25).eq_nbr = 25;
M_.aux_vars(26).endo_index = 158;
M_.aux_vars(26).type = 6;
M_.aux_vars(26).eq_nbr = 26;
M_.aux_vars(27).endo_index = 159;
M_.aux_vars(27).type = 6;
M_.aux_vars(27).eq_nbr = 27;
M_.aux_vars(28).endo_index = 160;
M_.aux_vars(28).type = 6;
M_.aux_vars(28).eq_nbr = 28;
M_.aux_vars(29).endo_index = 161;
M_.aux_vars(29).type = 6;
M_.aux_vars(29).eq_nbr = 29;
M_.aux_vars(30).endo_index = 162;
M_.aux_vars(30).type = 6;
M_.aux_vars(30).eq_nbr = 30;
M_.aux_vars(31).endo_index = 163;
M_.aux_vars(31).type = 6;
M_.aux_vars(31).eq_nbr = 31;
M_.aux_vars(32).endo_index = 164;
M_.aux_vars(32).type = 6;
M_.aux_vars(32).eq_nbr = 32;
M_.aux_vars(33).endo_index = 165;
M_.aux_vars(33).type = 6;
M_.aux_vars(33).eq_nbr = 33;
M_.aux_vars(34).endo_index = 166;
M_.aux_vars(34).type = 6;
M_.aux_vars(34).eq_nbr = 34;
M_.aux_vars(35).endo_index = 167;
M_.aux_vars(35).type = 6;
M_.aux_vars(35).eq_nbr = 35;
M_.aux_vars(36).endo_index = 168;
M_.aux_vars(36).type = 6;
M_.aux_vars(36).eq_nbr = 36;
M_.aux_vars(37).endo_index = 169;
M_.aux_vars(37).type = 6;
M_.aux_vars(37).eq_nbr = 37;
M_.aux_vars(38).endo_index = 170;
M_.aux_vars(38).type = 6;
M_.aux_vars(38).eq_nbr = 38;
M_.aux_vars(39).endo_index = 171;
M_.aux_vars(39).type = 6;
M_.aux_vars(39).eq_nbr = 39;
M_.aux_vars(40).endo_index = 172;
M_.aux_vars(40).type = 6;
M_.aux_vars(40).eq_nbr = 40;
M_.aux_vars(41).endo_index = 173;
M_.aux_vars(41).type = 6;
M_.aux_vars(41).eq_nbr = 41;
M_.aux_vars(42).endo_index = 174;
M_.aux_vars(42).type = 6;
M_.aux_vars(42).eq_nbr = 42;
M_.aux_vars(43).endo_index = 175;
M_.aux_vars(43).type = 6;
M_.aux_vars(43).eq_nbr = 43;
M_.aux_vars(44).endo_index = 176;
M_.aux_vars(44).type = 6;
M_.aux_vars(44).eq_nbr = 44;
M_.aux_vars(45).endo_index = 177;
M_.aux_vars(45).type = 6;
M_.aux_vars(45).eq_nbr = 45;
M_.aux_vars(46).endo_index = 178;
M_.aux_vars(46).type = 6;
M_.aux_vars(46).eq_nbr = 46;
M_.aux_vars(47).endo_index = 179;
M_.aux_vars(47).type = 6;
M_.aux_vars(47).eq_nbr = 47;
M_.aux_vars(48).endo_index = 180;
M_.aux_vars(48).type = 6;
M_.aux_vars(48).eq_nbr = 48;
M_.aux_vars(49).endo_index = 181;
M_.aux_vars(49).type = 6;
M_.aux_vars(49).eq_nbr = 49;
M_.aux_vars(50).endo_index = 182;
M_.aux_vars(50).type = 6;
M_.aux_vars(50).eq_nbr = 50;
M_.aux_vars(51).endo_index = 183;
M_.aux_vars(51).type = 6;
M_.aux_vars(51).eq_nbr = 51;
M_.aux_vars(52).endo_index = 184;
M_.aux_vars(52).type = 6;
M_.aux_vars(52).eq_nbr = 52;
M_.aux_vars(53).endo_index = 185;
M_.aux_vars(53).type = 6;
M_.aux_vars(53).eq_nbr = 53;
M_.aux_vars(54).endo_index = 186;
M_.aux_vars(54).type = 6;
M_.aux_vars(54).eq_nbr = 54;
M_.aux_vars(55).endo_index = 187;
M_.aux_vars(55).type = 6;
M_.aux_vars(55).eq_nbr = 55;
M_.aux_vars(56).endo_index = 188;
M_.aux_vars(56).type = 6;
M_.aux_vars(56).eq_nbr = 56;
M_.aux_vars(57).endo_index = 189;
M_.aux_vars(57).type = 6;
M_.aux_vars(57).eq_nbr = 57;
M_.aux_vars(58).endo_index = 190;
M_.aux_vars(58).type = 6;
M_.aux_vars(58).eq_nbr = 58;
M_.aux_vars(59).endo_index = 191;
M_.aux_vars(59).type = 6;
M_.aux_vars(59).eq_nbr = 59;
M_.aux_vars(60).endo_index = 192;
M_.aux_vars(60).type = 6;
M_.aux_vars(60).eq_nbr = 60;
M_.aux_vars(61).endo_index = 193;
M_.aux_vars(61).type = 6;
M_.aux_vars(61).eq_nbr = 61;
M_.aux_vars(62).endo_index = 194;
M_.aux_vars(62).type = 6;
M_.aux_vars(62).eq_nbr = 62;
M_.aux_vars(63).endo_index = 195;
M_.aux_vars(63).type = 6;
M_.aux_vars(63).eq_nbr = 63;
M_.aux_vars(64).endo_index = 196;
M_.aux_vars(64).type = 6;
M_.aux_vars(64).eq_nbr = 64;
M_.aux_vars(65).endo_index = 197;
M_.aux_vars(65).type = 6;
M_.aux_vars(65).eq_nbr = 65;
M_.aux_vars(66).endo_index = 198;
M_.aux_vars(66).type = 6;
M_.aux_vars(66).eq_nbr = 66;
M_.aux_vars(67).endo_index = 199;
M_.aux_vars(67).type = 6;
M_.aux_vars(67).eq_nbr = 67;
M_.aux_vars(68).endo_index = 200;
M_.aux_vars(68).type = 6;
M_.aux_vars(68).eq_nbr = 68;
M_.aux_vars(69).endo_index = 201;
M_.aux_vars(69).type = 6;
M_.aux_vars(69).eq_nbr = 69;
M_.aux_vars(70).endo_index = 202;
M_.aux_vars(70).type = 6;
M_.aux_vars(70).eq_nbr = 70;
M_.aux_vars(71).endo_index = 203;
M_.aux_vars(71).type = 6;
M_.aux_vars(71).eq_nbr = 71;
M_.aux_vars(72).endo_index = 204;
M_.aux_vars(72).type = 6;
M_.aux_vars(72).eq_nbr = 72;
M_.aux_vars(73).endo_index = 205;
M_.aux_vars(73).type = 6;
M_.aux_vars(73).eq_nbr = 73;
M_.aux_vars(74).endo_index = 206;
M_.aux_vars(74).type = 6;
M_.aux_vars(74).eq_nbr = 74;
M_.aux_vars(75).endo_index = 207;
M_.aux_vars(75).type = 6;
M_.aux_vars(75).eq_nbr = 75;
M_.aux_vars(76).endo_index = 208;
M_.aux_vars(76).type = 6;
M_.aux_vars(76).eq_nbr = 76;
M_.aux_vars(77).endo_index = 209;
M_.aux_vars(77).type = 6;
M_.aux_vars(77).eq_nbr = 77;
M_.aux_vars(78).endo_index = 210;
M_.aux_vars(78).type = 6;
M_.aux_vars(78).eq_nbr = 78;
M_.aux_vars(79).endo_index = 211;
M_.aux_vars(79).type = 6;
M_.aux_vars(79).eq_nbr = 79;
M_.aux_vars(80).endo_index = 212;
M_.aux_vars(80).type = 6;
M_.aux_vars(80).eq_nbr = 80;
M_.aux_vars(81).endo_index = 213;
M_.aux_vars(81).type = 6;
M_.aux_vars(81).eq_nbr = 81;
M_.aux_vars(82).endo_index = 214;
M_.aux_vars(82).type = 6;
M_.aux_vars(82).eq_nbr = 82;
M_.aux_vars(83).endo_index = 215;
M_.aux_vars(83).type = 6;
M_.aux_vars(83).eq_nbr = 83;
M_.aux_vars(84).endo_index = 216;
M_.aux_vars(84).type = 6;
M_.aux_vars(84).eq_nbr = 84;
M_.aux_vars(85).endo_index = 217;
M_.aux_vars(85).type = 6;
M_.aux_vars(85).eq_nbr = 85;
M_.aux_vars(86).endo_index = 218;
M_.aux_vars(86).type = 6;
M_.aux_vars(86).eq_nbr = 86;
M_.aux_vars(87).endo_index = 219;
M_.aux_vars(87).type = 6;
M_.aux_vars(87).eq_nbr = 87;
M_.aux_vars(88).endo_index = 220;
M_.aux_vars(88).type = 6;
M_.aux_vars(88).eq_nbr = 88;
M_.aux_vars(89).endo_index = 221;
M_.aux_vars(89).type = 6;
M_.aux_vars(89).eq_nbr = 89;
M_.aux_vars(90).endo_index = 222;
M_.aux_vars(90).type = 6;
M_.aux_vars(90).eq_nbr = 90;
M_.aux_vars(91).endo_index = 223;
M_.aux_vars(91).type = 6;
M_.aux_vars(91).eq_nbr = 91;
M_.aux_vars(92).endo_index = 224;
M_.aux_vars(92).type = 6;
M_.aux_vars(92).eq_nbr = 92;
M_.aux_vars(93).endo_index = 225;
M_.aux_vars(93).type = 6;
M_.aux_vars(93).eq_nbr = 93;
M_.aux_vars(94).endo_index = 226;
M_.aux_vars(94).type = 6;
M_.aux_vars(94).eq_nbr = 94;
M_.aux_vars(95).endo_index = 227;
M_.aux_vars(95).type = 6;
M_.aux_vars(95).eq_nbr = 95;
M_.aux_vars(96).endo_index = 228;
M_.aux_vars(96).type = 6;
M_.aux_vars(96).eq_nbr = 96;
M_.aux_vars(97).endo_index = 229;
M_.aux_vars(97).type = 6;
M_.aux_vars(97).eq_nbr = 97;
M_.aux_vars(98).endo_index = 230;
M_.aux_vars(98).type = 6;
M_.aux_vars(98).eq_nbr = 98;
M_.aux_vars(99).endo_index = 231;
M_.aux_vars(99).type = 6;
M_.aux_vars(99).eq_nbr = 99;
M_.aux_vars(100).endo_index = 232;
M_.aux_vars(100).type = 6;
M_.aux_vars(100).eq_nbr = 100;
M_.aux_vars(101).endo_index = 233;
M_.aux_vars(101).type = 6;
M_.aux_vars(101).eq_nbr = 101;
M_.aux_vars(102).endo_index = 234;
M_.aux_vars(102).type = 6;
M_.aux_vars(102).eq_nbr = 102;
M_.aux_vars(103).endo_index = 235;
M_.aux_vars(103).type = 6;
M_.aux_vars(103).eq_nbr = 103;
M_.aux_vars(104).endo_index = 236;
M_.aux_vars(104).type = 6;
M_.aux_vars(104).eq_nbr = 104;
M_.aux_vars(105).endo_index = 237;
M_.aux_vars(105).type = 6;
M_.aux_vars(105).eq_nbr = 105;
M_.aux_vars(106).endo_index = 238;
M_.aux_vars(106).type = 6;
M_.aux_vars(106).eq_nbr = 106;
M_.aux_vars(107).endo_index = 239;
M_.aux_vars(107).type = 6;
M_.aux_vars(107).eq_nbr = 107;
M_.aux_vars(108).endo_index = 240;
M_.aux_vars(108).type = 6;
M_.aux_vars(108).eq_nbr = 108;
M_.aux_vars(109).endo_index = 241;
M_.aux_vars(109).type = 6;
M_.aux_vars(109).eq_nbr = 109;
M_.aux_vars(110).endo_index = 242;
M_.aux_vars(110).type = 6;
M_.aux_vars(110).eq_nbr = 110;
M_.aux_vars(111).endo_index = 243;
M_.aux_vars(111).type = 6;
M_.aux_vars(111).eq_nbr = 111;
M_.aux_vars(112).endo_index = 244;
M_.aux_vars(112).type = 6;
M_.aux_vars(112).eq_nbr = 112;
M_.aux_vars(113).endo_index = 245;
M_.aux_vars(113).type = 6;
M_.aux_vars(113).eq_nbr = 113;
M_.aux_vars(114).endo_index = 246;
M_.aux_vars(114).type = 6;
M_.aux_vars(114).eq_nbr = 114;
M_.aux_vars(115).endo_index = 247;
M_.aux_vars(115).type = 6;
M_.aux_vars(115).eq_nbr = 115;
M_.aux_vars(116).endo_index = 248;
M_.aux_vars(116).type = 6;
M_.aux_vars(116).eq_nbr = 116;
M_.aux_vars(117).endo_index = 249;
M_.aux_vars(117).type = 6;
M_.aux_vars(117).eq_nbr = 117;
M_.aux_vars(118).endo_index = 250;
M_.aux_vars(118).type = 6;
M_.aux_vars(118).eq_nbr = 118;
M_.aux_vars(119).endo_index = 251;
M_.aux_vars(119).type = 6;
M_.aux_vars(119).eq_nbr = 119;
M_.aux_vars(120).endo_index = 252;
M_.aux_vars(120).type = 6;
M_.aux_vars(120).eq_nbr = 120;
M_.aux_vars(121).endo_index = 253;
M_.aux_vars(121).type = 6;
M_.aux_vars(121).eq_nbr = 121;
M_.aux_vars(122).endo_index = 254;
M_.aux_vars(122).type = 6;
M_.aux_vars(122).eq_nbr = 122;
M_.aux_vars(123).endo_index = 255;
M_.aux_vars(123).type = 6;
M_.aux_vars(123).eq_nbr = 123;
M_.aux_vars(124).endo_index = 256;
M_.aux_vars(124).type = 6;
M_.aux_vars(124).eq_nbr = 124;
M_.aux_vars(125).endo_index = 257;
M_.aux_vars(125).type = 6;
M_.aux_vars(125).eq_nbr = 125;
M_.aux_vars(126).endo_index = 258;
M_.aux_vars(126).type = 6;
M_.aux_vars(126).eq_nbr = 126;
M_.aux_vars(127).endo_index = 259;
M_.aux_vars(127).type = 6;
M_.aux_vars(127).eq_nbr = 127;
M_.aux_vars(128).endo_index = 260;
M_.aux_vars(128).type = 6;
M_.aux_vars(128).eq_nbr = 128;
M_.aux_vars(129).endo_index = 261;
M_.aux_vars(129).type = 6;
M_.aux_vars(129).eq_nbr = 129;
M_.aux_vars(130).endo_index = 262;
M_.aux_vars(130).type = 6;
M_.aux_vars(130).eq_nbr = 130;
M_.aux_vars(131).endo_index = 263;
M_.aux_vars(131).type = 6;
M_.aux_vars(131).eq_nbr = 131;
M_.aux_vars(132).endo_index = 264;
M_.aux_vars(132).type = 6;
M_.aux_vars(132).eq_nbr = 132;
M_.Sigma_e = zeros(4, 4);
M_.Correlation_matrix = eye(4, 4);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 0;
erase_compiled_function('RP_omega_static');
erase_compiled_function('RP_omega_dynamic');
M_.orig_eq_nbr = 132;
M_.eq_nbr = 264;
M_.ramsey_eq_nbr = 132;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 1 106 370;
 0 107 0;
 0 108 0;
 2 109 0;
 3 110 371;
 0 111 0;
 0 112 0;
 0 113 0;
 0 114 0;
 0 115 372;
 0 116 373;
 4 117 374;
 5 118 0;
 0 119 0;
 0 120 0;
 0 121 375;
 0 122 0;
 6 123 376;
 0 124 0;
 7 125 377;
 0 126 0;
 0 127 0;
 0 128 0;
 0 129 378;
 0 130 0;
 0 131 0;
 0 132 0;
 0 133 0;
 8 134 379;
 0 135 0;
 9 136 0;
 10 137 0;
 11 138 0;
 0 139 0;
 0 140 380;
 0 141 381;
 0 142 0;
 0 143 382;
 0 144 383;
 12 145 0;
 13 146 0;
 14 147 384;
 0 148 0;
 0 149 0;
 0 150 0;
 0 151 0;
 15 152 385;
 0 153 0;
 16 154 0;
 0 155 0;
 0 156 386;
 0 157 387;
 0 158 388;
 0 159 389;
 0 160 390;
 0 161 391;
 0 162 392;
 0 163 393;
 0 164 394;
 0 165 395;
 0 166 396;
 0 167 397;
 0 168 398;
 0 169 399;
 0 170 400;
 0 171 401;
 0 172 402;
 0 173 403;
 0 174 404;
 0 175 405;
 0 176 406;
 0 177 407;
 0 178 408;
 0 179 409;
 0 180 410;
 0 181 411;
 0 182 412;
 0 183 413;
 0 184 414;
 0 185 415;
 0 186 416;
 0 187 417;
 0 188 418;
 0 189 419;
 0 190 420;
 0 191 421;
 0 192 422;
 0 193 423;
 0 194 424;
 0 195 0;
 0 196 425;
 0 197 426;
 0 198 427;
 0 199 428;
 0 200 429;
 0 201 430;
 0 202 431;
 0 203 432;
 0 204 433;
 0 205 434;
 0 206 435;
 0 207 436;
 0 208 437;
 0 209 438;
 0 210 439;
 0 211 440;
 0 212 441;
 0 213 442;
 0 214 443;
 0 215 444;
 0 216 445;
 0 217 446;
 0 218 447;
 0 219 448;
 0 220 449;
 0 221 450;
 0 222 451;
 0 223 452;
 0 224 453;
 0 225 454;
 0 226 455;
 0 227 456;
 0 228 457;
 0 229 458;
 0 230 459;
 0 231 460;
 0 232 461;
 0 233 462;
 0 234 463;
 0 235 0;
 0 236 464;
 0 237 0;
 17 238 465;
 0 239 0;
 0 240 0;
 18 241 0;
 19 242 0;
 0 243 466;
 0 244 0;
 20 245 0;
 21 246 0;
 0 247 467;
 0 248 0;
 22 249 0;
 23 250 0;
 0 251 468;
 0 252 0;
 0 253 0;
 0 254 0;
 0 255 0;
 0 256 0;
 0 257 0;
 0 258 0;
 0 259 0;
 0 260 469;
 0 261 470;
 0 262 0;
 0 263 0;
 0 264 0;
 0 265 471;
 0 266 472;
 0 267 0;
 0 268 0;
 0 269 0;
 0 270 473;
 24 271 0;
 0 272 474;
 0 273 0;
 0 274 0;
 0 275 475;
 0 276 476;
 0 277 477;
 0 278 0;
 0 279 0;
 0 280 0;
 0 281 0;
 0 282 0;
 0 283 0;
 0 284 0;
 0 285 0;
 0 286 478;
 0 287 0;
 25 288 0;
 26 289 0;
 27 290 0;
 28 291 0;
 29 292 0;
 30 293 0;
 31 294 0;
 32 295 0;
 33 296 0;
 34 297 0;
 35 298 0;
 36 299 0;
 37 300 0;
 38 301 0;
 39 302 0;
 40 303 0;
 41 304 0;
 42 305 0;
 43 306 0;
 44 307 0;
 45 308 0;
 46 309 0;
 47 310 0;
 48 311 0;
 49 312 0;
 50 313 0;
 51 314 0;
 52 315 0;
 53 316 0;
 54 317 0;
 55 318 0;
 56 319 0;
 57 320 0;
 58 321 0;
 59 322 0;
 60 323 0;
 61 324 0;
 62 325 0;
 63 326 0;
 64 327 0;
 65 328 0;
 66 329 0;
 67 330 0;
 68 331 0;
 69 332 0;
 70 333 0;
 71 334 0;
 72 335 0;
 73 336 0;
 74 337 0;
 75 338 0;
 76 339 0;
 77 340 0;
 78 341 0;
 79 342 0;
 80 343 0;
 81 344 0;
 82 345 0;
 83 346 0;
 84 347 0;
 85 348 0;
 86 349 0;
 87 350 0;
 88 351 0;
 89 352 0;
 90 353 0;
 91 354 0;
 92 355 0;
 93 356 0;
 94 357 0;
 95 358 0;
 96 359 0;
 97 360 0;
 98 361 0;
 99 362 0;
 100 363 0;
 101 364 0;
 102 365 0;
 103 366 0;
 104 367 0;
 0 368 479;
 105 369 0;]';
M_.nstatic = 58;
M_.nfwrd   = 101;
M_.npred   = 96;
M_.nboth   = 9;
M_.nsfwrd   = 110;
M_.nspred   = 105;
M_.ndynamic   = 206;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:4];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(264, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(4, 1);
M_.params = NaN(50, 1);
M_.NNZDerivatives = [921; 1534; -1];
M_.params( 48 ) = 0.00000000000000;
sigmaqe = M_.params( 48 );
M_.params( 49 ) = 0.9000;
rhoqe = M_.params( 49 );
M_.params( 1 ) = 0.6500;
habit = M_.params( 1 );
M_.params( 2 ) = 0.9950;
bet = M_.params( 2 );
M_.params( 3 ) = 0.0200;
delta = M_.params( 3 );
M_.params( 4 ) = 0.00183221900000;
reta = M_.params( 4 );
M_.params( 5 ) = 0.4550;
psi_l = M_.params( 5 );
M_.params( 6 ) = 0.4290;
elas_l = M_.params( 6 );
M_.params( 9 ) = 1.0049629;
pi_ss = M_.params( 9 );
M_.params( 27 ) = 0.9000;
lam_r = M_.params( 27 );
M_.params( 28 ) = 1.19;
lam_pi = M_.params( 28 );
M_.params( 29 ) = 0.176;
lam_y = M_.params( 29 );
Rd_temp = pi_ss/bet;
M_.params( 10 ) = 21.0;
xi_w = M_.params( 10 );
M_.params( 11 ) = 0.6400;
phi_w = M_.params( 11 );
M_.params( 16 ) = 6.0000;
xi_p = M_.params( 16 );
M_.params( 17 ) = 0.6000;
phi_p = M_.params( 17 );
M_.params( 18 ) = M_.params(16)/(M_.params(16)-1);
mark_p = M_.params( 18 );
M_.params( 12 ) = M_.params(10)/(M_.params(10)-1);
mark_w = M_.params( 12 );
M_.params( 13 ) = 0.9000;
eta_h = M_.params( 13 );
M_.params( 14 ) = 0.0700;
eta_e = M_.params( 14 );
M_.params( 15 ) = 1-M_.params(13)-M_.params(14);
eta_b = M_.params( 15 );
M_.params( 20 ) = 0.63999900000000;
theta_h = M_.params( 20 );
M_.params( 19 ) = 0.36000000000000;
theta_k = M_.params( 19 );
M_.params( 21 ) = (1.0-M_.params(20)-M_.params(19))/2.0;
theta_e = M_.params( 21 );
M_.params( 22 ) = 1.0-M_.params(20)-M_.params(19)-M_.params(21);
theta_b = M_.params( 22 );
M_.params( 24 ) = 0.35000000000000;
delalpha = M_.params( 24 );
M_.params( 25 ) = 0.70000000000000;
tau_b = M_.params( 25 );
M_.params( 26 ) = 0.70000000000000;
tau_e = M_.params( 26 );
M_.params( 23 ) = 1.0200000000000;
bigR = M_.params( 23 );
M_.params( 31 ) = 0.0000;
bby = M_.params( 31 );
M_.params( 32 ) = 1.00000000000000;
nu = M_.params( 32 );
M_.params( 33 ) = 0.95000000000000;
rhoz = M_.params( 33 );
M_.params( 36 ) = 0.010000000000;
sigmaz = M_.params( 36 );
sigma_a = 0.50000000000000;
M_.params( 34 ) = 0.00000000000000;
rhomp = M_.params( 34 );
M_.params( 37 ) = 0.010000000000;
sigmamp = M_.params( 37 );
M_.params( 35 ) = 0.90000000000000;
rhobk = M_.params( 35 );
M_.params( 38 ) = 0.90000000000000;
sigmabk = M_.params( 38 );
M_.params( 39 ) = 0.99300000000000;
alpha_ss = M_.params( 39 );
M_.params( 46 ) = 15.0000000000000;
Chi = M_.params( 46 );
M_.params( 43 ) = 10.0000000000000;
epsb = M_.params( 43 );
M_.params( 44 ) = 3.800;
Btopbar = M_.params( 44 );
M_.params( 45 ) = 0.0000;
Blowbar = M_.params( 45 );
M_.params( 41 ) = (-5.00000000000000);
omega = M_.params( 41 );
M_.params( 42 ) = 0.01000000000000;
varsigma = M_.params( 42 );
M_.params( 40 ) = 0.02500000000000;
mu_ss = M_.params( 40 );
alphatemp = alpha_ss;
mutemp = mu_ss;
smallbtemp = Btopbar*(1+Chi*mutemp)^(-epsb);
kk1 = delta*theta_k/(alphatemp*bigR*(1/bet-1+delta)); 
betatemp  = 1/bet;
infl_temp = pi_ss;
qtemp = kk1*(alphatemp*tau_b*mutemp*betatemp/delalpha-(1+mutemp+alphatemp*mutemp/(Rd_temp*delalpha)));
qtemp = qtemp/(alphatemp*smallbtemp*kk1/(Rd_temp*delalpha)-alphatemp*bigR*kk1/Rd_temp-theta_e-theta_b-bby-alphatemp*tau_e*smallbtemp*kk1*betatemp/delalpha);
Gtemp = 1+mutemp-(qtemp*alphatemp/Rd_temp)*(bigR-mutemp/(qtemp*delalpha)-smallbtemp/delalpha);
IY = kk1/qtemp;
KY = alphatemp*bigR*IY/delta; 
KeY = tau_e*alphatemp*smallbtemp*IY/delalpha;
KbY = tau_b*alphatemp*mutemp*IY/(qtemp*delalpha);
KhY = KY - KeY - KbY;
CeY = (1-tau_e)*alphatemp*smallbtemp*IY*qtemp/delalpha;
CbY = nu*(1-tau_b)*alphatemp*mutemp*IY/delalpha;
ChY = 1 + bby - CeY - CbY  - (1+mutemp)*IY;
essai = (1-bet*habit)*theta_h/((1-habit)*ChY*psi_l*mark_w);
smallh = essai^(1/(1+elas_l));
Htemp = smallh*eta_h^(xi_w/(xi_w-1));
kk2 = (KY^(1/(1-theta_k))) * (eta_e^(theta_e/(1-theta_k)))* (eta_b^(theta_b/(1-theta_k)))* mark_p^(1/(theta_k-1));
Ktemp = Htemp^(theta_h/(1-theta_k))* kk2;
Ytemp = (1/mark_p)* (Ktemp^theta_k)*(Htemp^theta_h)*(eta_e^theta_e)*(eta_b^theta_b);
M_.params( 30 ) = (M_.params(18)-1)*Ytemp;
bigtheta = M_.params( 30 );
Itemp = IY*Ytemp;
rktemp = (1/mark_p)*theta_k*(Ktemp^(theta_k-1))*(Htemp^theta_h)*(eta_e^theta_e)*(eta_b^theta_b);
M_.params( 7 ) = rktemp;
chi1 = M_.params( 7 );
M_.params( 8 ) = sigma_a*M_.params(7);
chi2 = M_.params( 8 );
w_htemp = (1/mark_p)*theta_h*(Ktemp^theta_k)*(Htemp^(theta_h-1))*(eta_e^theta_e)*(eta_b^theta_b);
w_etemp = (1/mark_p)*theta_e*(Ktemp^theta_k)*(Htemp^theta_h)*(eta_e^(theta_e-1))*(eta_b^theta_b);
w_btemp = (1/mark_p)*theta_b*(Ktemp^theta_k)*(Htemp^theta_h)*(eta_e^theta_e)*(eta_b^(theta_b-1));
Ketemp = KeY*Ytemp;
Kbtemp = KbY*Ytemp;
Khtemp = KhY*Ytemp;
Cetemp = CeY*Ytemp;
Cbtemp = CbY*Ytemp;
chtemp = ChY*Ytemp/eta_h;
bigAtemp = eta_b*w_btemp+(rktemp+qtemp*(1-delta))*Kbtemp+bby*Ytemp;
bigNtemp = eta_e*w_etemp+(rktemp+qtemp*(1-delta))*Ketemp;
totCtemp = Cetemp+Cbtemp+eta_h*chtemp;
lamtemp = (1-bet*habit)/((1-habit)*(chtemp));
smalldtemp = alphatemp*qtemp*( bigR - smallbtemp/delalpha - mutemp/(qtemp*delalpha))*Itemp/(Rd_temp*eta_b);
ptemp = (Rd_temp-1)*lamtemp/ ( (Rd_temp-1)*lamtemp*eta_b*smalldtemp + eta_h*reta);
mctemp = reta*ptemp/((Rd_temp-1)*lamtemp);
Ratemp = alphatemp*qtemp*(mutemp/(qtemp*delalpha))*Itemp/bigAtemp;
TLtemp = Itemp-bigNtemp;
wtildetemp = w_htemp*infl_temp*eta_h^(-1/(1-xi_w));
numwtemp =  ( ( (w_htemp*infl_temp)^(xi_w*(1+elas_l)) * Htemp^(1+elas_l) )/(1-bet*phi_w) )^(1/(1+elas_l*xi_w));
denwtemp = ( (w_htemp^(xi_w)*infl_temp^(xi_w-1)*Htemp*lamtemp)/(1-bet*phi_w) )^(1/(1+elas_l*xi_w));
wtildetemp = (mark_w*psi_l)^(1/(1+xi_w*elas_l))*numwtemp/denwtemp;
stemp = 1/mark_p;
mgrowthtemp = infl_temp;
expinfltemp = infl_temp;
gYtemp = 1;
utemp = 1;
gammagtemp = (Itemp-bigNtemp )/bigAtemp;
resid;
steady;
oo_.dr.eigval = check(M_,options_,oo_);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = M_.params(36)^2;
M_.Sigma_e(2, 2) = M_.params(37)^2;
M_.Sigma_e(3, 3) = M_.params(38)^2;
M_.Sigma_e(4, 4) = M_.params(48)^2;
M_.ramsey_model_constraints = {
{16, '>', '1'}
};
M_.params( 50 ) = 1;
optimal_policy_discount_factor = M_.params( 50 );
options_.nograph = 1;
options_.instruments = char('gammag');
var_list_ = char();
ramsey_policy(var_list_);
eliminate_lagrange_multipliers;
save('RP_omega_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('RP_omega_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('RP_omega_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('RP_omega_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('RP_omega_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('RP_omega_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('RP_omega_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
